### PR TITLE
September_2022 Blog

### PR DESCRIPTION
**Pull request by MDeexith**
Issue No : #1 

# Work

- Created new blog on artificial intelligence
- Added latest news

### CODE REVIEW

**Comment by kunalagra** [comment]
Fantastic Work @MDeexith. Just a Small Change that I would suggest, re-arrange 3rd & 4th to be at last as to provide a nice closure to the Edittion. 
Rest All Seems Good.

**Comment by MDeexith** [comment]
I made changes according to your suggestions.
Please review and merge.

**Comment by kunalagra** [comment]
Great. The blog clearly summarizes all the best news of Sept 22. 
Thanks for the work.

**Comment by kunalagra** [comment]
Hey @MDeexith Please reformat the Image "Fig1_A.png" as the Hugo Build is failing. Raise a new appropriate PR to fix this.

**Pull request merged**
